### ISSUE TITLE
Unable to locate package openjdk-8-jdk

### ISSUE THREAD

**Issue by 87abhii** [Springjunky/docker-local-build-environment#3]
root@bpi-x:/home/bpi-x/docker-bpi-master#
root@bpi-x:/home/bpi-x/docker-bpi-master# docker-compose up --build -d
Building postgres
Step 1/3 : FROM postgres
 ---> 30121e967865
Step 2/3 : COPY createSonar.sql /docker-entrypoint-initdb.d/
 ---> Using cache
 ---> 08bc8779f1dc
Step 3/3 : COPY createKeycloak.sql /docker-entrypoint-initdb.d/
 ---> Using cache
 ---> d3c5179dbbe4
Successfully built d3c5179dbbe4
Successfully tagged dockerbpimaster_postgres:latest
Building gitlabrunner
Step 1/5 : FROM gitlab/gitlab-runner
 ---> b3476023f6bd
Step 2/5 : ADD entrypointAutoregister /
 ---> Using cache
 ---> c2f438e1aa49
Step 3/5 : RUN chmod +x /entrypointAutoregister
 ---> Using cache
 ---> 33a918a00b66
Step 4/5 : ENTRYPOINT ["/usr/bin/dumb-init", "/entrypointAutoregister"]
 ---> Using cache
 ---> 4d902c3fdbf6
Step 5/5 : CMD ["run", "--user=gitlab-runner", "--working-directory=/home/gitlab-runner"]
 ---> Using cache
 ---> 3ca2ec60809c
Successfully built 3ca2ec60809c
Successfully tagged dockerbpimaster_gitlabrunner:latest
Building jenkins
Step 1/55 : FROM ubuntu:17.10
 ---> 1af812152d85
Step 2/55 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 7216ce270244
Step 3/55 : ENV JAVA_VERSION=8     JAVA_UPDATE=131     JAVA_BUILD=11     JAVA_HOME="/usr/lib/jvm/default-jvm"
 ---> Using cache
 ---> 46242aa81feb
Step 4/55 : RUN apt-get update
 ---> Using cache
 ---> 2fd20655b6fa
Step 5/55 : RUN apt-get install -y openjdk-8-jdk
 ---> Running in e2adf32f5ea2
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package openjdk-8-jdk
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c apt-get install -y openjdk-8-jdk' returned a non-zero code: 100
root@bpi-x:/home/bpi-x/docker-bpi-master# cd jenkins-fat/

**Comment by Springjunky** [comment]
This clould be a caching problem of the intermediate containers, try to build from scratch... 


#### delete all downloaded images and ALL intermediate images
docker rmi -f $(docker images  -aq)

#### delete all the container 
docker container rm $(docker container ls -aq)

#### delete the unused volumes
docker volume prune 

.... and try again 








This is my log after removing this ... the apt-get update GET's many urls

Step 3/55 : ENV JAVA_VERSION=8     JAVA_UPDATE=131     JAVA_BUILD=11     JAVA_HOME="/usr/lib/jvm/default-jvm"
 ---> Running in 51c10a6e2f7c
Removing intermediate container 51c10a6e2f7c
 ---> ea3c940d8848
Step 4/55 : RUN apt-get update
 ---> Running in 422c71785e2b
Get:1 http://archive.ubuntu.com/ubuntu artful InRelease [237 kB]
Get:2 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
Get:4 http://security.ubuntu.com/ubuntu artful-security/universe Sources [14.4 kB]
Get:5 http://security.ubuntu.com/ubuntu artful-security/universe amd64 Packages [66.3 kB]
Get:6 http://archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
Get:7 http://security.ubuntu.com/ubuntu artful-security/restricted amd64 Packages [2931 B]
Get:8 http://security.ubuntu.com/ubuntu artful-security/multiverse amd64 Packages [1824 B]
Get:9 http://security.ubuntu.com/ubuntu artful-security/main amd64 Packages [180 kB]
Get:10 http://archive.ubuntu.com/ubuntu artful/universe Sources [11.1 MB]
Get:11 http://archive.ubuntu.com/ubuntu artful/main amd64 Packages [1416 kB]
Get:12 http://archive.ubuntu.com/ubuntu artful/multiverse amd64 Packages [185 kB]
Get:13 http://archive.ubuntu.com/ubuntu artful/universe amd64 Packages [10.8 MB]
Get:14 http://archive.ubuntu.com/ubuntu artful/restricted amd64 Packages [14.7 kB]
Get:15 http://archive.ubuntu.com/ubuntu artful-updates/universe Sources [33.5 kB]
Get:16 http://archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages [292 kB]
Get:17 http://archive.ubuntu.com/ubuntu artful-updates/universe amd64 Packages [121 kB]
Get:18 http://archive.ubuntu.com/ubuntu artful-updates/restricted amd64 Packages [2931 B]
Get:19 http://archive.ubuntu.com/ubuntu artful-updates/multiverse amd64 Packages [1824 B]
Get:20 http://archive.ubuntu.com/ubuntu artful-backports/main amd64 Packages [1469 B]
Get:21 http://archive.ubuntu.com/ubuntu artful-backports/universe amd64 Packages [4102 B]
Fetched 24.6 MB in 22s (1094 kB/s)
Reading package lists...
Removing intermediate container 422c71785e2b
 ---> 116f70691b95
Step 5/55 : RUN apt-get install -y openjdk-8-jdk
 ---> Running in 2d9b4f4d973a
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  adwaita-icon-theme at-spi2-core ca-certificates ca-certificates-java dbus
  fontconfig fontconfig-config fonts-dejavu-core fonts-dejavu-extra

**Comment by Springjunky** [comment]
I guess its solved ... closed
