### ISSUE TITLE
cheksum issue

### ISSUE THREAD

**Issue by pacificpaudel** [Springjunky/docker-local-build-environment#5]
Step 37/52 : RUN echo Download from ${JENKINS_URL} &&     curl -fL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war &&     echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha1sum -c -
 ---> Running in dc9bc88b029b
Download from http://updates.jenkins-ci.org/download/war/2.190.3/jenkins.war
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   244  100   244    0     0    628      0 --:--:-- --:--:-- --:--:--   628
100   252  100   252    0     0    292      0 --:--:-- --:--:-- --:--:--     0
100 74.6M  100 74.6M    0     0   139k      0  0:09:08  0:09:08 --:--:-- 41527
/usr/share/jenkins/jenkins.war: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
ERROR: Service 'jenkins' failed to build: The command '/bin/sh -c echo Download from ${JENKINS_URL} &&     curl -fL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war &&     echo "${JENKINS_SHA}  /usr/share/jenkins/jenkins.war" | sha1sum -c -' returned a non-zero code: 1

**Comment by Springjunky** [comment]
Fixed
